---
title: "Climate Crisis Iteration 1 Measurement Model Evaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(seminr)
library(data.table)
library(DT)
library(htmltools)
model <- readRDS("model-cc-1.RDS")
bootmodel <- readRDS("model-boot-cc-1.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumfsbo <- summary(bootmodel$first_stage_model)
```

# Model plots
## Original Estimate Model
```{r plot model, echo=FALSE}
plot(model, title = "Original Estimate Model", theme = seminr_theme_smart())
```
## Bootstrapped Model
```{r plot bootmodel, echo=FALSE}
plot(bootmodel, title = "Bootstrapped Model")
```
# Measurement Model Only
```{r plot mm model, echo=FALSE}
plot(bootmodel, measurement_only = TRUE)
```
```{r eval-df, echo = FALSE}
# Base DF
evalmm <- data.frame(Construct = model$mmMatrix[,1],
                           Type = ifelse(grepl("HOCA", model$mmMatrix[,3]),
                                         "HOC", "Construct"),
                           Mode = dplyr::recode(model$mmMatrix[,3],
                                         "A" = "reflective",
                                         "B" = "formative",
                                         "HOCA" = "higher-order"),
                           Indicator.or.LOC = model$mmMatrix[,2])

# hocevalmm1 <- evalmm %>% filter(Mode == "higher-order")%>% rename(LOC = Indicator.or.LOC) %>% mutate(Type = NULL)
# unique(hocevalmmcc1$Construct)
# forevalmmcc1 <- evalmmcc1 %>% filter(Mode == "formative") %>% rename(Indicator = Indicator.or.LOC) %>% mutate(Type = NULL)
# forevalmmcc1

```
# Evaluation of the reflective measurement model
Loadings should be 
```{r ref-eval, echo = FALSE}
refevalmmbase <- evalmm %>% filter(Mode == "reflective") %>% rename(Indicator = Indicator.or.LOC) %>% 
  mutate(Type = NULL, Mode = NULL)
refloadings <- c()
for (i in 1:nrow(refevalmmbase)){
  refloadings <<- append(refloadings, sumfs$loadings[refevalmmbase$Indicator[i], refevalmmbase$Construct[i]])
}

cicr <- data.frame(Construct = row.names(sumfs$reliability), 
                   AVE = as.numeric(sumfs$reliability[,3]), 
                   Calpha = as.numeric(sumfs$reliability[,1]),
                   rhoC = as.numeric(sumfs$reliability[,2]))
#Next step is HTMT
boothtmtbase <- data.frame(Construct.Rel. = row.names(sumbomo$bootstrapped_HTMT),
                          Lower.CI = as.numeric(sumbomo$bootstrapped_HTMT[,5]),
                          Upper.CI = as.numeric(sumbomo$bootstrapped_HTMT[,6]))
#For HTMT evaluation, one should consider only reflective constructs - and HOCs with reflective LOCs
htmtvec <- c(unique(refevalmmbase$Construct), 
             unlist(unique(evalmm %>% filter(Indicator.or.LOC %in% unique(refevalmmbase$Construct)) %>% select("Construct"))))
# Transform "Relationships" Column into two distinct columns
boothtmtsplit <- base::strsplit(boothtmtbase$Construct.Rel., "  ->  ")
boothtmtsplit1 <- c()
boothtmtsplit2 <- c()
for (i in 1:length(boothtmtsplit)){
 boothtmtsplit1 <<- append(boothtmtsplit1, boothtmtsplit[[i]][1])
 boothtmtsplit2 <<- append(boothtmtsplit2, boothtmtsplit[[i]][2])
}
boothtmt <- (boothtmtbase %>% mutate(Construct.Rel. = NULL, Construct.1 = boothtmtsplit1, Construct.2 = boothtmtsplit2))[,c(3:4,1:2)] %>%
  filter(Construct.1 %in% htmtvec & Construct.2 %in% htmtvec)
maxhtmtbase <- data.frame(Construct = boothtmt[,1], Max.HTMT =  boothtmt[,4]) %>% 
  rbind(data.frame(Construct = boothtmt[,2], Max.HTMT =  boothtmt[,4])) %>%
  group_by(Construct) %>%
  summarise(Max.HTMT = max(Max.HTMT)) %>%
  mutate('1.in.HTMT.CI' = ifelse(Max.HTMT >=1, TRUE, FALSE))
`%notin%` <- Negate(`%in%`)
maxhtmt <- evalmm[,c(1,4)] %>% filter(Indicator.or.LOC %in% unique(refevalmmbase$Construct)) %>%
  rbind(data.frame(Construct = unique(refevalmmbase$Construct[refevalmmbase$Construct %notin% evalmm$Indicator.or.LOC]),
                   Indicator.or.LOC = unique(refevalmmbase$Construct[refevalmmbase$Construct %notin% evalmm$Indicator.or.LOC]))) %>%
  left_join(maxhtmtbase) %>% 
  mutate(Construct = Indicator.or.LOC, Indicator.or.LOC = NULL)

# Make final data frame
refevalmm <- refevalmmbase %>% cbind(Loadings = refloadings) %>% left_join(cicr) %>% left_join(maxhtmt[,c(1,3)])
datatable(refevalmm) %>%
  formatRound(3:6,
              digits = 3)
```

```{r ref-eval-HTMT,echo=FALSE}
#If there are problems with the HTMT, here is a detailed table
datatable(boothtmt) %>%
  formatRound(3:4,
              digits = 3)
```

