---
title: "Model Comparison"
output: html_document
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Include libraries
library(tidyverse)
library(seminr)
library(DT)
library(htmltools)
# Set seminr plot theme
thm <- seminr_theme_create(construct.compositeA.arrow = "backward", construct.compositeA.use_weights = FALSE, plot.adj = TRUE)
seminr_theme_set(thm)
# My favorite operator
`%notin%` <- Negate(`%in%`)
```

Here, we compare all Climate Crisis Models.
```{r comparison table, echo=FALSE, include=FALSE}
# Rows should be R²adj and plspredict comp
# Cols should be model
comparison <- data.frame(Category = c("R²adj Behavioral Intention", 
                                      "R²adj Response Beliefs", 
                                      "R²adj Threat Beliefs",
                                      "R²adj Perceived Self-Efficacy",
                                      "R²adj Perceived Response Efficacy",
                                      "R²adj Perceived Response Costs",
                                      "R²adj Perceived Susceptibility",
                                      "R²adj Perceived Severity",
                                      "PLSpredict PLS>LM RMSE",
                                      "PLSpredict PLS>LM MAD"))
```

<!-- # Model Insertion Template -->
<!-- ```{r model Insert mdodelname, echo=FALSE, include =FALSE} -->
<!-- # Define model name -->
<!-- modelname <- "" -->
<!-- # Load models and create summaries -->
<!-- model <- readRDS() -->
<!-- bootmodel <- readRDS() -->
<!-- bootfsmodel <- readRDS() -->
<!-- proxymodel <- readRDS() -->
<!-- summo <- summary(model) -->
<!-- sumfs <- summary(model$first_stage_model) -->
<!-- sumbomo <- summary(bootmodel) -->
<!-- sumbofsmo <- summary(bootfsmodel) -->
<!-- # Create R²adj df -->
<!-- r2hoc <- data.frame(Construct = colnames(summo$paths), -->
<!--                     "AdjR^2" = summo$paths[2,]) -->
<!-- r2loc <- data.frame(Construct = colnames(sumfs$paths), -->
<!--                     "AdjR^2" = sumfs$paths[2,]) %>% -->
<!--   filter(Construct %notin% r2hoc$Construct) -->
<!-- # Insert Model name here -->
<!-- r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct), -->
<!--                                           modelname = AdjR.2) -->
<!-- colnames(r2adj)[2] <- modelname -->
<!-- # Create plspredict df -->
<!-- plspre <- predict_pls(proxymodel, noFolds = 10) -->
<!-- sumplspre <- summary(plspre) -->
<!-- oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>% -->
<!--   rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>% -->
<!--   rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>% -->
<!--   rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>% -->
<!--   cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)] -->
<!-- plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE", -->
<!--                                     "PLSpredict PLS>LM MAD"), -->
<!--                        modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]), -->
<!--                                      sum(oospp[6,-1]>0)/ncol(oospp[,-1]))) -->
<!-- colnames(plspredf)[2] <- modelname -->
<!-- # create modelsum and join it with comparison df -->
<!-- modelsum <- union(r2adj, plspredf) -->
<!-- comparison <- comparison %>% left_join(modelsum) -->
<!-- ``` -->
<!-- ```{r visualize model insert modelname, echo=FALSE} -->
<!-- plot(bootmodel, structure_only = TRUE, title = modelname) -->
<!-- ``` -->


```{r model Insert Model Climate Crisis 2-a-2, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-a-2 (Diet)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-a-2.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-a-2.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-a-2.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-a-2.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize model Model Climate Crisis 2-a-2, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```
```{r model Insert Model Climate Crisis 2-a-3-a-1, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-a-3-a-1 (Diet)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-a-3-a-1.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-a-3-a-1.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-a-3-a-1.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-a-3-a-1.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize Model Climate Crisis 2-a-3-a-1, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```
```{r model Insert Model Climate Crisis 2-a-3-b-1, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-a-3-b-1 (Diet)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-a-3-b-1.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-a-3-b-1.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-a-3-b-1.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-a-3-b-1.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize Model Climate Crisis 2-a-3-b-1, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```


```{r model Climate Crisis-2-b-3-a-2, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-b-3-a-2 (Heating)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-b-3-a-2.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-b-3-a-2.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-b-3-a-2.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-b-3-a-2.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize model Climate Crisis-2-b-3-a-2, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```

```{r model Climate Crisis-2-b-3-b-2, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-b-3-b-2 (Heating)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-b-3-b-2.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-b-3-b-2.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-b-3-b-2.RDS")
summo <- summary(model)
sumbomo <- summary(bootmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
# Insert Model name here
r2adj <- r2hoc %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize model Climate Crisis-2-b-3-b-2, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```
```{r model Climate Crisis-2-c-3, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-c-3 (Driving)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-c-3.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-c-3.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-c-3.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-c-3.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize model Climate Crisis-2-c-3, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```
```{r model Climate Crisis-2-c-4, echo=FALSE, include =FALSE}
# Define model name
modelname <- "Model Climate Crisis 2-c-4 (Driving)"
# Load models and create summaries
model <- readRDS("Models/model-cc-2-c-4.RDS")
bootmodel <- readRDS("Models/model-boot-cc-2-c-4.RDS")
bootfsmodel <- readRDS("Models/model-fs-boot-cc-2-c-4.RDS")
proxymodel <- readRDS("Models/model-proxy-cc-2-c-4.RDS")
summo <- summary(model)
sumfs <- summary(model$first_stage_model)
sumbomo <- summary(bootmodel)
sumbofsmo <- summary(bootfsmodel)
# Create R²adj df
r2hoc <- data.frame(Construct = colnames(summo$paths),
                    "AdjR^2" = summo$paths[2,])
r2loc <- data.frame(Construct = colnames(sumfs$paths),
                    "AdjR^2" = sumfs$paths[2,]) %>%
  filter(Construct %notin% r2hoc$Construct)
# Insert Model name here
r2adj <- union(r2hoc, r2loc) %>% transmute(Category = paste0("R²adj ", Construct),
                                          modelname = AdjR.2)
colnames(r2adj)[2] <- modelname
# Create plspredict df
plspre <- predict_pls(proxymodel, noFolds = 10)
sumplspre <- summary(plspre)
oospp <- (as.data.frame(sumplspre$PLS_out_of_sample) %>%
  rbind(as.data.frame(sumplspre$LM_out_of_sample)) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[1,] - (as.data.frame(sumplspre$PLS_out_of_sample))[1,]) %>%
  rbind((as.data.frame(sumplspre$LM_out_of_sample))[2,] - (as.data.frame(sumplspre$PLS_out_of_sample))[2,])  %>%
  cbind(`Prediction Errors` = c("PLS RMSE", "PLS MAD", "LM RMSE", "LM MAD", "RMSE Difference", "MAD Difference")))[c(1,3,5,2,4,6),c(4,1:3)]
plspredf <- data.frame(Category = c("PLSpredict PLS>LM RMSE",
                                    "PLSpredict PLS>LM MAD"),
                       modelname = c(sum(oospp[3,-1]>0)/ncol(oospp[,-1]),
                                     sum(oospp[6,-1]>0)/ncol(oospp[,-1])))
colnames(plspredf)[2] <- modelname
# create modelsum and join it with comparison df
modelsum <- union(r2adj, plspredf)
comparison <- comparison %>% left_join(modelsum)
```
```{r visualize model Climate Crisis-2-c-4, echo=FALSE}
plot(bootmodel, structure_only = TRUE, title = modelname)
```

```{r comparison table print, echo=FALSE}
# Transpose df for styling
comparisont <- as.data.frame(t(comparison[,-1]))
colnames(comparisont) <- comparison[,1]
comparisont <- cbind(data.frame(Model = colnames(comparison)[-1]), comparisont)
datatable(comparisont,
          rownames = FALSE,
          caption = "Model Comparison") %>% 
  formatRound(-1,
              digits = 3) %>%
  formatStyle(colnames(comparisont)[2], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,2], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[3], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,3], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[4], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,4], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[5], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,5], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[6], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,6], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[7], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,7], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[8], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,8], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[9], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,9], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[10], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,10], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6'))) %>%
  formatStyle(colnames(comparisont)[11], backgroundColor = styleInterval(cuts = c(round(max(comparisont[,11], na.rm = TRUE), digits = 3)-0.001), values = c('#00','#add8e6')))
```

